### ISSUE TITLE
Flutter: Check Device Available Storage using Dart

### ISSUE THREAD

**Issue by juralak** [appium/appium-flutter-driver#442] opened 2023-03-29 02:30 UTC
What should I do when I try to connect Appium to an application developed by Flutter on iOS?

I problem issue related to this error.

<img width="685" alt="Screen Shot 2566-03-28 at 17 01 28" src="https://user-images.githubusercontent.com/58243930/228411022-0a5772b4-a887-49ca-8058-7031fee89ff7.png">

how to solve this problem.

**Comment by KazuCocoa** [comment] 2023-03-29 08:22
Perhaps you can check if the systemlog has the observatory URL. 1.14.3 has a debug log around there, so it also could help.

**Comment by juralak** [comment] 2023-03-29 08:53
Hello, I'm not sure what this version 1.14.3 is referring to?

To elaborate on the issue, I am planning to develop automated tests using Robot Framework for an application developed using Flutter. Building the application for Android does not pose any problems, but building it for iOS results in issues as outlined in the problem topic.

please, help me solve issue TT

**Comment by juralak** [comment] 2023-04-05 04:05
> I meant Appium Flutter Driver > 1.14.3
> 
> For iOS, it has a known limitation such as #115

Oh!! this issue #445 , They are facing the same problem as me.

**Comment by KazuCocoa** [comment] 2023-08-28 07:58
Duplicate of https://github.com/appium/appium-flutter-driver/issues/445 as the last comment

**Closed by KazuCocoa** 2023-08-28 07:58 UTC
Labels: question
