### ISSUE TITLE
Keyboard is not working after adding enableFlutterDriverExtension()

### ISSUE THREAD

**Issue by Vladeezyy** [appium/appium-flutter-driver#607] opened 2023-10-21 22:05 UTC
I am trying to test form_app from Flutter app examples: https://github.com/flutter/samples/tree/main/form_app

Here is what i have in pubspec.yml:

```
dev_dependencies:
  analysis_defaults:
    path: ../analysis_defaults
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
```

main.dart file:

```
import 'dart:io' show Platform;
import 'package:flutter_driver/driver_extension.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:window_size/window_size.dart';

import 'src/autofill.dart';
import 'src/form_widgets.dart';
import 'src/http/mock_client.dart';
import 'src/sign_in_http.dart';
import 'src/validation.dart';

void main() {
  enableFlutterDriverExtension();
  setupWindow();
  runApp(const FormApp());
}
```

And now after running the test, keyboard of the app is not appearing. 

I have flutter driver 1.23.0, appium 2.2.0 (have tried latest flutter driver but the same result)

Here is my capabs for device:

```
config.capabilities = [
    {
        platformName: "Android",
        maxInstances: 1,
        "appium:deviceName": "emulator-5554",
        "appium:platformVersion": "12.0",
        "appium:orientation": "PORTRAIT",
        "appium:automationName": "Flutter",
        "appium:app": join("./apk/", APP_ANDROID || ""),
        //"acceptInsecureCerts": true,
        // @ts-ignore
        "appium:newCommandTimeout": 240,
    },
];
```

here is my appium log attached:

[appium.log](https://github.com/appium/appium-flutter-driver/files/13061906/appium.log)

have tried different versions of android, recreating emulators, nothing helps.
But if i change the main.dart file to:

```
import 'dart:io' show Platform;
import 'package:flutter_driver/driver_extension.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:window_size/window_size.dart';

import 'src/autofill.dart';
import 'src/form_widgets.dart';
import 'src/http/mock_client.dart';
import 'src/sign_in_http.dart';
import 'src/validation.dart';

void main() {
  setupWindow();
  enableFlutterDriverExtension(); //! THIS IS THE CHANGE
  runApp(const FormApp());
}
```

Now keyboard works but I cannot connect to Dart Observatory anymore it shows 
"ext.flutter.driver" is not found in "extensionRPCs"  error in log
What can be a problem here?

**Comment by KazuCocoa** [comment] 2023-10-22 06:44
Duplicate of https://github.com/appium/appium-flutter-driver/issues/602
It looks like https://api.flutter.dev/flutter/flutter_driver/flutter_driver-library.html 's limitation, this driver depends on.

**Closed by KazuCocoa** 2023-10-22 06:44 UTC

**Comment by Vladeezyy** [comment] 2023-10-22 16:05
@KazuCocoa so then I don't have the option to make it working at all?

**Comment by KazuCocoa** [comment] 2023-10-22 19:25
For keycode, I wondered if https://github.com/appium/appium-flutter-driver/issues/602#issuecomment-1774013975 might help.

In general key type except for the adb command, I'm afraide no. If you do not need flutter native something, Appium UIA2 driver helps without flutter driver preparation. https://github.com/appium/appium-flutter-driver?tab=readme-ov-file#appium-flutter-driver-or-appium-uiautomator2xcuitest-driver

**Comment by Vladeezyy** [comment] 2023-10-22 19:57
@KazuCocoa Thanks for answer, here what I have:
keyboard is not appearing if enableFlutterDriver is the first one (before widgets init and runApp()), but im able to enter a data to fields using 
`driver.sendKeys()`, so actually I think it's okay and I can automate functionality like that.
